name: 'Validate Version Tag'
description: 'Validates a version tag.'
inputs:
  ref_name:
    required: true
  branch:
    required: true
  tags:
    required: false
    default: '^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
outputs:
  current_version:
    description: 'The current version.'
  previous_version:
    description: 'The next-highest version after the current one.'
runs:
  using: 'node16'
  main: 'src/index.js'
